#icon_theme = "Paper"

popup_autohide = true
position = "top"

### Start ###
[[start]]
type = "notifications"
[[start]]
type = "brightness"
[[start]]
type = "volume"
max_volume = 150
[[start]]
type = "clipboard"

### Center ###
[[center]]
type = "focused"
show_title = false

[[center]]
type = "workspaces"
all_monitors = false
favorites = ["1", "2", "3"]

[[center]] # Apps
type = "launcher"

[[center]]
type = "focused"
show_title = false


### End ###
[[end]]
class = "network-menu"
type = "custom"
[[end.bar]]
type = "network_manager"
[[end.bar]]
type = "button"
label = ""
on_click = "!nm-connection-editor"


[[end]]
type = "clock"

[[end]]
# FIXME: install upower
type = "battery"

[[end]]
class = 'power-menu'
type = 'custom'
[[end.bar]]
label = ''
name = 'power-btn'
on_click = '!wleave'
type = 'button'
