#icon_theme = "Paper"

popup_autohide = true
position = "top"

### Start ###
[[start]]
type = "notifications"
[[start]]
type = "brightness"
[[start]]
type = "volume"
max_volume = 150

[[center]]
type = "workspaces"
all_monitors = false
favorites = ["1", "2", "3"]

### Center ###
[[center]] # Apps
type = "launcher"


### End ###
[[end]]
class = "network-menu"
type = "custom"
[[end.bar]]
# TODO: idk bro fix it
type = "network_manager"
on_click = "nm-connection-editor"
[end.bar.profiles.wifi_connected]
when = { type = "wifi", state = "connected" }
icon = "󰖩"
[end.bar.profiles.wifi_disconnected]
when = { type = "wifi", state = "disconnected" }
icon = "󰖪"
[end.bar.profiles.wired_connected]
when = { type = "wired", state = "connected" }
icon = "󰈀"
[end.bar.profiles.wired_disconnected]
when = { type = "wired", state = "disconnected" }
icon = "󰌙"

#[[end.bar]]
#type = "button"
#label = ""
#on_click = "!nm-connection-editor"

#[[end.bar]]


[[end]]
type = "clock"

[[end]]
# FIXME: install upower
type = "battery"

[[end]]
class = 'power-menu'
type = 'custom'
[[end.bar]]
label = ''
name = 'power-btn'
on_click = '!wleave'
type = 'button'
