[[bar.layout]]
monitor = "*"
left = ["custom-power-menu", "brightness", "volume", "systray"]
center = ["mango-workspaces", "window-title"]
right = ["ram", "cpu", "network", "clock", "battery", "dashboard"]

[modules.mango-workspaces]
app-icons-show = true

[modules.window-title]
label-show = false

[[modules.custom]]
id = "power-menu"
icon-name = "ld-power-symbolic"
label-show = false
left-click = "wleave"
# Todo: Clipboard
# Todo: Quotes
