[[bar.layout]]
monitor = "*"
left = ["custom-power-menu", "brightness", "volume", "systray"]
center = ["niri-workspaces", "window-title"]
right = ["ram", "cpu", "network", "clock", "battery", "dashboard"]

[modules.niri-workspaces]
app-icons-show = true
hide-trailing-empty = false

[modules.window-title]
label-show = false

[[modules.custom]]
id = "power-menu"
icon-name = "ld-power-symbolic"
label-show = false
left-click = "wleave"
# Todo: Clipboard
# Todo: Quotes
